### ISSUE TITLE
Buildroot bringup

### ISSUE THREAD

**Issue by Vignesh-Vadivel** [Vignesh-Vadivel/final-project-assignment-vignesh-vadivel#2]
Create a build root repository for the project, targeting hardware Raspberry Pi 3B.

DoD : 
1. Complete the setup and build.sh shall be completed successfully
2. Resulting build shall generate a sdcard.img
3. flash the img on on the sd card
4. Check the output flashed img

Blockers : None

**Comment by Nileshkartik95** [comment]
1. Build root setup is complete.
2. Reference https://github.com/cu-ecen-aeld/buildroot-assignments-base/wiki/Setting-up-Buildroot-for-Hardware-Builds
3. Please refer https://github.com/cu-ecen-aeld/final-project-Nileshkartik95 and commit [c6168fc4363000ef297de26a328aee3f70c53c63](https://github.com/cu-ecen-aeld/final-project-Nileshkartik95/commit/c6168fc4363000ef297de26a328aee3f70c53c63)
4. Please refer the below image for buildroot setup

![Image](https://user-images.githubusercontent.com/112504087/232374712-55f5aca4-f36a-4acd-b416-f2821f4a7ce3.jpg)


DoD:
1. Complete the setup and build.sh shall be completed successfully (Verified)
2. Resulting build shall generate a sdcard.img (Verified)
3. flash the img on on the sd card (Verified)
4. Check the output flashed img (Verified)
