### ISSUE TITLE
Sending a Static Image over Socket

### ISSUE THREAD

**Issue by Vignesh-Vadivel** [Vignesh-Vadivel/final-project-assignment-vignesh-vadivel#3]
DOD:  
1. Establish Socket Connection between 2 devices over TCP  
2. Test the connecting by sending few data  
3. Send one static image over socket and Recreate same image on the client Pi  

Blocker: None

**Comment by Nileshkartik95** [comment]
Socket Client and server code is Complete, Need to Multithread it with the GPIO and OLED in future sprint.
Please refer the Client Source Code at https://github.com/cu-ecen-aeld/final-project-Vignesh-Vadivel/tree/master/Client and commit https://github.com/cu-ecen-aeld/final-project-Vignesh-Vadivel/commit/ab088e79ef0091a8bc469ca09b64e5e0d2ef5fe6
Please refer the Server Source Code at https://github.com/cu-ecen-aeld/final-project-Vignesh-Vadivel/tree/master/Server and commit https://github.com/cu-ecen-aeld/final-project-Vignesh-Vadivel/commit/0fe50acb3fc32445a881a4d8551955f9250c95d9

Please refer the below image for the image sent from socket 

![Image](https://user-images.githubusercontent.com/112504087/233900215-f3dc5cdd-1433-4ad4-a964-0575ce4ba5e6.png)

Please refer the below image for the image received over client 

![Image](https://user-images.githubusercontent.com/112504087/233900063-b4e37fbc-4a39-446a-98ff-9843b87462b0.png)



    1. Establish Socket Connection between 2 devices over TCP (verified)
    2. Test the connecting by sending few data (verified)
    3. Send one static image over socket and Recreate same image on the client Pi (Verified)


Blocker : Buildroot image although recognizes logitech keyboard, keyboard inputs were not working for the USB bluetooth receiver, we were in an assumption that buildroot image was not flashed properly, later we tried replacing the keyboard with the wired one and it started working
