### ISSUE TITLE
OLED Bringup for Client Node

### ISSUE THREAD

**Issue by Vignesh-Vadivel** [Vignesh-Vadivel/final-project-assignment-vignesh-vadivel#5]
DoD:
OLED displays Lane Keep warnings for the images sent over socket.
OLED displays normal drive condition when recovered.

Blocker:
None

**Comment by Nileshkartik95** [comment]
OLED Code is Complete
Please refer the Client Source Code at https://github.com/cu-ecen-aeld/final-project-Vignesh-Vadivel/tree/master/Client and commit https://github.com/cu-ecen-aeld/final-project-Vignesh-Vadivel/commit/75d9fd178dce0b217e5e0b8c46dd53e6692fa87c

Please refer the below image for the OLED bringup

![Image](https://user-images.githubusercontent.com/112504087/235517851-e577b9d9-a30c-4a14-98a8-e3218a112cd5.png)

OLED displays Lane Keep warnings for the images sent over socket.(Verified)
OLED displays normal drive condition when recovered.(Verified)
