### ISSUE TITLE
Buzzer Setup for Client Node

### ISSUE THREAD

**Issue by Vignesh-Vadivel** [Vignesh-Vadivel/final-project-assignment-vignesh-vadivel#6]
DoD:
Buzzer ON Lane Keep warnings for the images sent over socket.
Buzzer OFF normal drive condition when recovered.

Blocker :
None

**Comment by Nileshkartik95** [comment]
Buzzer Code is Complete
Please refer the Client Source Code at https://github.com/cu-ecen-aeld/final-project-Vignesh-Vadivel/tree/master/Client and commit https://github.com/cu-ecen-aeld/final-project-Vignesh-Vadivel/commit/2fd8df2190f03455a649653949eb398b848c5cee

Buzzer ON Lane Keep warnings for the images sent over socket. (Verified)
Buzzer OFF normal drive condition when recovered.(Verified)

Blocker: None
