### ISSUE TITLE
Ensure that data coherency is maintained in the client side

### ISSUE THREAD

**Issue by Vignesh-Vadivel** [Vignesh-Vadivel/final-project-assignment-vignesh-vadivel#8]
DoD: -  
1. Implement multi threading in client side code.  
2. One thread will control buzzer and the other thread will control the oled.  

Blockers:-  
None

**Comment by Nileshkartik95** [comment]
Code Integration is Complete and Data Coherency is maintained
Please refer the Client Source Code at https://github.com/cu-ecen-aeld/final-project-Vignesh-Vadivel/tree/master/Client and commit https://github.com/cu-ecen-aeld/final-project-Vignesh-Vadivel/commit/2fd8df2190f03455a649653949eb398b848c5cee


Implement multi threading in client side code.(Verified)
One thread will control buzzer and the other thread will control the oled. (Verified)
